apiVersion: v1
kind: Service
metadata:
  name: {{ include "py-kms.fullname" . }}
  labels:
    {{- include "py-kms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.kms.type }}
  ports:
    - port: {{ .Values.service.kms.port }}
      targetPort: kms
      protocol: TCP
      name: kms
      {{- if contains "NodePort" .Values.service.kms.type }}
      Nodeport: {{ .Values.service.kms.nodePort }}
      {{- end }}
  selector:
    {{- include "py-kms.selectorLabels" . | nindent 4 }}
