apiVersion: v1
kind: Service
metadata:
  name: {{ include "py-kms.fullname" . }}-gui
  labels:
    {{- include "py-kms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.gui.type }}
  ports:
    - port: {{ .Values.service.gui.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "py-kms.selectorLabels" . | nindent 4 }}
