{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bulwark-webmail.fullname" . }}
  labels:
    {{- include "bulwark-webmail.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.sessionSecret }}
  SESSION_SECRET: {{ .Values.secret.sessionSecret | quote }}
  {{- end }}
  {{- if .Values.secret.oauthClientId }}
  OAUTH_CLIENT_ID: {{ .Values.secret.oauthClientId | quote }}
  {{- end }}
  {{- if .Values.secret.oauthClientSecret }}
  OAUTH_CLIENT_SECRET: {{ .Values.secret.oauthClientSecret | quote }}
  {{- end }}
{{- end }}
