{{- range $key, $value := .Values.namespaces }}
{{- if eq ( .enabled | toString) "true" }}
{{- if and .secrets .secrets.opaque }}
{{- range .secrets.opaque }}
{{- $name := .name | required "name is required for secret." }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | replace "_" "-" | lower | quote }}
  namespace: {{ $value.name | replace "_" "-" | quote }}
type: Opaque
data:
  {{- range $k, $v := .data }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- if and .secrets .secrets.dockerconfig }}
{{- range .secrets.dockerconfig }}
{{- $name := .name | required "name is required for secret." }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | replace "_" "-" | lower | quote }}
  namespace: {{ $value.name | replace "_" "-" | quote }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths": {
      {{ .hostname | quote }}: {
        "auth": {{ .auth | quote }}
      }
    }}
{{- end }}
{{- end }}
{{- if and .secrets .secrets.tls }}
{{- range .secrets.tls }}
{{- $name := .name | required "name is required for secret." }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | replace "_" "-" | lower | quote }}
  namespace: {{ $value.name | replace "_" "-" | quote }}
{{- if and .cert .key }}
type: kubernetes.io/tls
{{- else }}
type: Opaque
{{- end }}
data:
  {{- if .cert }}
  tls.crt: {{ .cert | b64enc }}
  {{- end }}
  {{- if .key }}
  tls.key: {{ .key | b64enc }}
  {{- end }}
  {{- if .ca }}
  ca.crt: {{ .ca | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
