{{- range $key, $value := .Values.namespaces }}
{{ if eq ( .enabled | toString) "true" }}
{{ if and .vaultSecrets .vaultSecrets.secrets }}
{{- range .vaultSecrets.secrets }}
{{- $name := .name | required "name is required for vaultSecret." }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultsecret-{{ .name | replace "_" "-" | lower }}
  namespace: {{ $value.name | replace "_" "-" | quote }}
spec:
  type: {{ default "kv-v2" .type }}
  mount: {{ required "mount is required for VaultStaticSecret." .mount | quote }}
  path: {{ required "path is required for VaultStaticSecret." .path | quote }}
  refreshAfter: {{ default "3600s" .refreshAfter | quote }}
  vaultAuthRef: {{ required "auth is required for VaultStaticSecret." .auth | quote }}
  {{- if .namespace }}
  namespace: {{ .namespace | quote }}
  {{- end }}
  destination:
    name: {{ .name | replace "_" "-" | quote }}
    create: true
    type: {{ default "Opaque" .secretType }}
    {{- if .transformation }}
    transformation: {{ .transformation | toYaml | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
